#
# Makefile to build que wireless module inside the DEA build system
#
# "device/nxp/common/build/kernel.mk" should be included before this file
#

# Generic flags
KBUILD_OPTIONS := WLAN_ROOT=$(ANDROID_BUILD_TOP)/$(QCACLD_PATH)
KBUILD_OPTIONS += MODNAME=wlan
KBUILD_OPTIONS += WLAN_OPEN_SOURCE=1
KBUILD_OPTIONS += CONFIG_QCA_WIFI_ISOC=0
KBUILD_OPTIONS += CONFIG_QCA_WIFI_2_0=1
KBUILD_OPTIONS += CONFIG_QCA_CLD_WLAN=m
KBUILD_OPTIONS += CONFIG_NON_QC_PLATFORM=y
KBUILD_OPTIONS += CONFIG_LINUX_QCMBR=y
KBUILD_OPTIONS += BUILD_DEBUG_VERSION=0

ifeq ($(QCACLD_WIFI_INTERFACE), sdio)
KBUILD_OPTIONS += CONFIG_CLD_HL_SDIO_CORE=y
else ifeq ($(QCACLD_WIFI_INTERFACE), pci)
KBUILD_OPTIONS += CONFIG_ROME_IF=pci
KBUILD_OPTIONS += CONFIG_HIF_PCI=1
KBUILD_OPTIONS += CONFIG_ATH_PCIE_ACCESS_DEBUG=1
KBUILD_OPTIONS += CONFIG_ATH_PCIE_MAX_PERF=1
else
$(error Variable QCACLD_WIFI_INTERFACE not set.)
endif

ifeq ($(BOARD_HAVE_WIFI_QCA6574),true)
KBUILD_OPTIONS += CONFIG_ARCH_MSM=n
KBUILD_OPTIONS += CONFIG_ARCH_QCOM=n
KBUILD_OPTIONS += CONFIG_ATH_11AC_TXCOMPACT=1
endif

QCACLD_OUT := $(TARGET_OUT_INTERMEDIATES)/QCACLD_OBJ

$(QCACLD_OUT):
	mkdir -p $@

$(QCACLD_OUT)/wlan.ko: | $(QCACLD_OUT)
	@ $(kernel_build_shell_env) $(MAKE) $(kernel_build_make_env) \
		M=$(ANDROID_BUILD_TOP)/$(QCACLD_PATH) modules $(KBUILD_OPTIONS)
	cp $(ANDROID_BUILD_TOP)/$(QCACLD_PATH)/wlan.ko $@

.PHONY: qcacld
qcacld: $(QCACLD_OUT)/wlan.ko
